#!/bin/sh

 #pactl move-sink-input 82 alsa_output.pci-0000_00_1f.3.analog-stereo &&\
 #pactl move-sink-input 82 alsa_output.pci-0000_00_1f.3.hdmi-stereo-extra1 &&\
 #xrandr --output HDMI2 --off

hdmi_check=$(xrandr | grep ' connect' | grep 'HDMI' | awk '{print$1}')

[[ ! -z "$hdmi_check" ]] && xrandr --output HDMI2 --mode 1920x1080 || notify-send "No HDMI cable connected"
